### ISSUE TITLE
Shorten Variable Name Lengths, Remove Camel Casing, Standardize Prefixes

### ISSUE THREAD

**Issue by colinmacfarlane** [csg-org/esb-data-standard#15]
I believe the variable names should be shortened, moving away from descriptive variable names, to variable names that cater to leading analysis software. The four leading statistics programs are R, Stata, SPSS, and SAS. Of these, SPSS has a 64 character limit on variable names and Stata and SAS have a 32 character limit. The typical recommendation for a raw dataset is to shoot for an 8 character or less variable name. This is all helpful for many reasons - it reduces the amount of text needed in your syntax files. It also reduces errors from mistyping long variable names. More importantly, to generate new variable in a dataset, the analyst will want to add a prefix or suffix to the variable name, meaning the need to add letters onto the original variable names (ex: BallotRejectionType_new). 

Camel casing is helpful for readability, but annoying for writing analysis code. Most datasets will defer to a consistent variable capitalization strategy: all caps, all lowercase, or only capitalize the first letter. Most statistical programs are case sensitive, so if the analyst writes (ex: VoterId) the code will not run and he/she now has to memorize the camel casing (or more likely will just create their own variables with consistent casing).

Sorting is important for variable name. I would recommend that your variable names can always be sorted from left to right, where similar variables tack on letters to the right. For example, by sorting alphabetically, I would want to know ApplicationRequestRejectionOtherType is related to ApplicationRequestRejectionType.

Below I suggest new variable names that are 1) shorter, 2) have consistent prefixes and suffixes, and 3) remove camel casing.

ID | Trans_id
VoterID | Voter_id
ApplicationRequestMethod | Appreqmeth
ApplicationRequestOtherMethod | Appreqmeth_oth
ApplicationRequestPostmarkDate | Appreqpostdate
ApplicationRequestProcessedDate | Appreqprocdate
ApplicationRequestReceivedDate | Appreqrecdate
ApplicationRequestRejectionType | Appreqrejtype
ApplicationRequestRejectionOtherType | Appreqrejtype_oth
ApplicationRequestStatusType | Appreqstatus
ApplicationRequestType | Appreqtype
BallotRejectionType | Ballrejtype
BallotRejectionOtherType | Ballrejtype_oth
BallotReturnDate | Ballretdate
BallotReturnType | Ballrettype
BallotReturnOtherType | Ballrettype_oth
BallotTransmissionDate | Balltrandate
BallotTransmissionType | Balltrantype
BallotTransmissionOtherType | Balltrantype_oth
BallotType | Balltype
ElectionDate | Elecdate
ElectionName | Elecname
JurisdictionId | Jur_id
JurisdictionIdType | Jurtype
JurisdictionName | Jurname
StateName | Statename
VoterMailingCountry | Country_mail
VoterType | Votertype
WasApplicationRejected | Appreqrej

**Comment by jungshadow** [comment]
While I understand the concern/frustration here, the point of this data standard isn't directly for analysis, but to provide an accessible vehicle for jurisdictions to standardize their existing data and provide it to us. Part of our approach ties back to my comment in #14 regarding the existing style guides. I assumed that there would be a intermediary standard for analysis that uses our standard as a baseline, but that falls outside our scope.

I'll admit to not knowing much about statistical programs, but could you replace/map the header to new values? Quick example below using R (I know you are using something else) to replace the header, wholesale:

```r
test <- read.csv("esbdata-2018-11-06-Colorado.csv", header=FALSE)
colnames(test) <- c("Trans_id", "Voter_id", "Appreqmeth", "Appreqmeth_oth",
        "Appreqpostdate", "Appreqprocdate", "Appreqrecdate", "Appreqrejtype",
        "Appreqrejtype_oth", "Appreqstatus", "Appreqtype", "Ballrejtype",
        "Ballrejtype_oth", "Ballretdate", "Ballrettype", "Ballrettype_oth",
        "Balltrandate", "Balltrantype", "Balltrantype_oth", "Balltype", "Elecdate",
        "Elecname", "Jur_id", "Jurtype", "Jurname", "Statename", "Country_mail",
        "Votertype", "Appreqrej")
```
