### ISSUE TITLE
Clarifying Type vs. Method vs. Mode

### ISSUE THREAD

**Issue by colinmacfarlane** [csg-org/esb-data-standard#16]
It is not consistent how we're using type and method across variables. In ApplicationRequestMethod, the values are email, fax, in-person, mail, online, phone, untracked, and other. In BallotReturnType and BallotTransmissionType, we use the same values but the variable name uses "type". In the literature, these are also usually all called "modes". I recommend either changing all of these variable name and descriptions (and their "other' variables") to ending with "Mode" or "Method", preferably mode.

**Comment by jungshadow** [comment]
Hmmm...that's a fair suggestion. Our naming convention became muddled, a bit, when we were trying to follow the [VIP style guide on its treatment of types](https://github.com/votinginfoproject/vip-specification/blob/vip52/STYLEGUIDE.md#type-names). I'm open to discussing this. I'm also thinking we need to pull in the VIP style guide and modify it to fit our needs if we feel the need to branch off.

@JDziurlaj, any additional thoughts?

**Comment by jungshadow** [comment]
This should be fixed with the changes proposed in #32.

**Comment by JDziurlaj** [comment]
The use of the modifier `method` was decided upon.
