### ISSUE TITLE
Add Election Type

### ISSUE THREAD

**Issue by colinmacfarlane** [csg-org/esb-data-standard#17]
If the standard could potentially collect primary and General Election data, it seems necessary to distinguish between the two. One locality had this issue in 2016. I recommend the following variable:

**Descriptive Name:** Election Type
**Variable Name:** Electype
**Data Type:** numeric
**Required:** Yes
**Values:** 1: General Election; 2: Primary Election; 3: Special Election/Other; -99: Missing; -101: Missing – Juris Field; -999: Error: Out of Range Value
**Description:** Specifies whether the transaction was collected for either a Primary Election or the General Election. For example, the ballot was requested, transmitted, returned, or rejected for a primary or General Election.

Recommend dropping ElectionName. In 2016, the values entered were varied such as "General", "Presidential General Election", "Nov General 2016", "2016 -county name- County General Election". All of this we should already know if we have a variables that collect the year, the state name, the county name, and the election type. There was one recall election specified in 2016 that may be worth discussing.

**Comment by jungshadow** [comment]
I'm honestly fine with this change and happy to incorporate it during the next revamp, assuming the jurisdictions are ok with it. I am changing the naming convention to match the standard style, changing to string, and removing the additional error/missing values as I believe they are a usability issue (i.e. they won't have semantic meaning to the election officials and I'm concerned that it will result in higher data errors):

> **Descriptive Name:** Election Type
> **Variable Name:** ElectionType
> **Data Type:** String
> **Required:** Yes
> **Values:** general; primary; special; other
> **Description:** Specifies whether the transaction was collected for either a Primary Election or the General Election. For example, the ballot was requested, transmitted, returned, or rejected for a Primary, General, Special, or other type of Election.

@JDziurlaj Feel free to chime in if you have other thoughts on this.

**Comment by JDziurlaj** [comment]
I would probably start with the [enumeration from ERR CDF](https://github.com/usnistgov/ElectionResultsReporting/blob/version2/Election_Results_Reporting_UML_documentation.md#_17_0_2_4_78e0236_1389734457182_720347_3938), and restrict it somewhat.
