### ISSUE TITLE
Making missingValues explicit in documentation

### ISSUE THREAD

**Issue by JDziurlaj** [csg-org/esb-data-standard#21]
The feeds do not handle missing optional data consistently. The ESB specification is silent on this, while the `tableschema` specification allows a set of values to represent `missingValues`, which will be deserialized as `null`. My suggestion would be to formalize the empty string `""` as the value to provide when the a data field is not available for a record.

**Comment by jungshadow** [comment]
That works for me. Honestly, this seems like a change that we can make mid-cycle, if you feel it's worthwhile. If you think it can wait, we can add it to the backlog.

**Comment by JDziurlaj** [comment]
I think I'm going to modify my recommendation a tad. [Table Schema](https://frictionlessdata.io/specs/table-schema/) allows for multiple `missingValues` (it is an array), so I'm think we can be a little more nuanced. The new suggestion is:
- empty string `""` for *value not provided*
- `na` for explicit *not applicable / available* (open to other literal value ideas)

The processing tool will handle either the same way, (converting them to null in the programming language of choice), but this distinction provides better evidence of the intent behind the missing value. If approved, this will need to be documented in the specification as well.

**Comment by jungshadow** [comment]
We have an `untracked` enumeration value. Maybe that instead of `na`?

**Comment by JDziurlaj** [comment]
@jungshadow, unfortunately `untracked` won't work. The reason being that any value matching a literal in the `missingValues` array gets converted to `(null)`, so this would result in enumeration value of `untracked` getting converted to `(null)` as well. I'm still open to suggestions for an alternative value.
