### ISSUE TITLE
Expand VoterType enumerations

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#22]
The current values of `VoterType` generally define classes of UOCAVA voters, but avoid classes for military spouses or dependents. To capture this information, the new enumerations could be:

- `domestic-military`
- `domestic-military-spouse-dependent`
- `military`
- `military-spouse-dependent`
- `overseas-citizen`
- `overseas-military`
- `overseas-military-spouse-dependent`
- `other`

Given the lack of granularity on the [FPCA](https://www.fvap.gov/uploads/FVAP/Forms/fpca2013.pdf), it's unlikely that the enumerations could be broken down any more (i.e. `-spouse` and `-dependent`).

**Comment by JDziurlaj** [comment]
I see we've added `other` as well. What is the use-case for that enumeration literal?

**Comment by jungshadow** [comment]
Honestly, I wish I could tell you the use case. All I can tell you is that we keep having unexplained `other` voters, so I'm hesitant to take it away.

**Comment by JDziurlaj** [comment]
Resolved via PR #27
