### ISSUE TITLE
ApplicationRequestRejectionType is missing an 'untracked' enumeration value

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#24]
## Issue
`ApplicationRequestRejectionType` is missing 'untracked' as a potential enumeration value. Some states and jurisdictions do not track application "rejection" reasons.

## Solution
Add 'untracked' to the list of possible enumerations for `ApplicationRequestRejectionType`.

**Comment by jungshadow** [comment]
Since #25 is accepted, this issue may need to be modified or removed.

**Comment by JDziurlaj** [comment]
I think this gets implemented and added to the renamed field `RequestStatusRejectedType`.
