### ISSUE TITLE
Standardize casing of abbreviations

### ISSUE THREAD

**Issue by JDziurlaj** [csg-org/esb-data-standard#26]
Tableschema fields `ID`, and `VoterID` use uppercase abbreviations, however `JurisdictionId` and `JurisdictionIdType` use initcaps.

**Comment by JDziurlaj** [comment]
To clarify, this issue proposes to use InitCaps everywhere, so `ID` and `VoterID` would become `Id`, and `VoterId`, respectively.

**Comment by JDziurlaj** [comment]
Looking at the latest proposal for changes (#32), it appears the group settled on UPPER instead of InitCaps. Consistency is the most important thing, but I could note that the NIST specs (e.g. CVR) use InitCap, not UPPER for abbreviations.

**Comment by jungshadow** [comment]
@JDziurlaj, I have no horse in this race. As long as we're consistent, it works for me. Happy to follow the NIST specs here.
