### ISSUE TITLE
Rename tableschema fields for clarity

### ISSUE THREAD

**Issue by JDziurlaj** [csg-org/esb-data-standard#3]
`ApplicationType` – Recommend renaming to `ApplicationRequestType` (see below)
`ApplicationRequestType` – Recommend renaming to `ApplicationRequestMethod` 

This is to make the column names a little less ambiguous, IMO.

**Comment by jungshadow** [comment]
I agree. I'm aiming to try and follow the [VIP styleguide](https://github.com/votinginfoproject/vip-specification/blob/vip52/STYLEGUIDE.md) as much as possible. That means that some of the names are probably going to be a little confusing, but I think it's better to have a rationale behind certain decisions.
