### ISSUE TITLE
Model for the submission process

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#30]
Issue #29 made me think of this. Can we model a process for how jurisdictions will export and bundle their data and (eventually) submit to the FVAP portal? Trying to figure out ways we can make the process more accessible.

**Comment by JDziurlaj** [comment]
I just saw this (6 months later). Are you looking for a business process for submission from a jurisdiction to a portal?

**Comment by jungshadow** [comment]
@JDziurlaj Essentially. Some sort of a "how-to" on getting data out of a system, formatting it, testing it, and sending it to us, either through a (potential) portal or email. Something we can turn into a one-pager or post somewhere. We can gloss over some of the details that are nebulous (e.g. exporting from database) and maybe start from a point of "you have data that could match up with the standard." If there's some modeling involved as well, excellent.

**Comment by JDziurlaj** [comment]
This has been done and is available on Signavio.
