### ISSUE TITLE
Move to Voter Activity Model

### ISSUE THREAD

**Issue by JDziurlaj** [csg-org/esb-data-standard#32]
Make the following changes to the esb tableschema, including relevent updates to the embedded documentation (description).

- Rename `ApplicationRequestMethod` to `VoterActivityMethod`
- Remove `cured` from `VoterActivityMethod`
- Rename `ApplicationRequestOtherMethod` to `VoterActivityOtherMethod`
- Delete `ApplicationRequestPostmarkDate`
- Rename `ApplicationRequestProcessedDate` to `VoterActivityDate`
- Make `VoterActivityDate` required
- Delete `ApplicationRequestReceivedDate`
- Rename `ApplicationRequestRejectionType` to `VoterActivityStatusType`
- Remove `cured` from `VoterActivityStatusType`
- Add `VoterActivityStatusRejectedType`
- Rename `ApplicationRequestRejectionOtherType` to `VoterActivityStatusOtherType`
- Delete `ApplicationRequestStatusType`
- Rename `ApplicationRequestType` to `VoterActivityType`
- Rename `BallotReturnType` to `BallotReturnMethod`
- Rename `BallotReturnOtherType` to `BallotReturnOtherMethod`
- Rename `BallotTransmissionType` to `BallotTransmissionMethod`
- Rename `BallotTransmissionOtherType` to `BallotTransmissionOtherMethod`
- Rename `JurisdictionId` to `JurisdictionID`
- Rename `JurisdictionIdType` to `JurisdictionIDType`
- Add `UOCAVAFlagDate`

**Comment by jungshadow** [comment]
A few things here:
- `UOCAVAFlagDate` and `VoterActivityDate` should theoretically be the same thing. It largely comes down to naming convention. Do we want to explicitly call it out as UOCAVA-specific? Personally, I'd like to maintain how absentee-model-agnostic it is, but that may not be possible.
- The whole mess of `VoterActivityStatusRejectedType`, `VoterActivityStatusType`, and `VoterActivityStatusOtherType` needs some additional thinking/reworking...which is largely my fault for it being a mess. Can you take a stab at that?

Thoughts, @JDziurlaj?

**Comment by JDziurlaj** [comment]
One of the issues is that the terminology `VoterActivityX` implies the activity qualifies as "Voter Activity", if that's true, it doesn't make sense to reject it. However, if we label the fields as plain old `Activity`, then we can conditionally add the qualifier `Voter` (i.e. activity we care about). So perhaps:

Rename all fields from `VoterActivityX` to `ActivityX`
Rename `VoterActivityStatusType` to `VoterActivityQualificationStatusType`
Rename `VoterActivityStatusRejectedType` to `VoterActivityDisqualificationType`

`VoterActivityQualificationStatusType` would determine if the `Activity` is also `Voter Activity`, and probably change the enumeration values to `qualified`, `disqualified` (`unqualified`?)

**Comment by jungshadow** [comment]
I think this shows promise. @ctice5, @david-varas what do you think?

**Comment by JDziurlaj** [comment]
I think these changes make sense as a package.

**Comment by ctice5** [comment]
I think it makes sense and allows us to be more agnostic because (correct me if I'm wrong) that UOCAVA Flag date would only be appearing in all mail systems as opposed to traditional. My question is as to Pending under qualification status. Wouldn't that be similar to the cured issue we discussed previously?

**Comment by JDziurlaj** [comment]
Changing several of the fields from `ApplicationRequest` to `VoterActivity` has not been the most straightforward process. A lot of this comes down to the clumsy prose that must be written when things are put in terms of *activity* instead *request*. My understanding is this change was made to better comport with the way all-mail states operate. However, I think a side effect will be confusion for non-all-mail states, as voter activity usually has a different, particular meaning related to list maintenance (NVRA). I propose a compromise. We would rename `ApplicationRequest` to `Request` (or even `VoterRequest`). This makes the language a bit more inclusive, but still keeps things in terms of cause (request), rather than effect (activity).

**Comment by jungshadow** [comment]
@JDziurlaj I think I'm in favor of this. Can you provide a rough outline of the changes (kinda like the mapping I did in #25)?

**Comment by JDziurlaj** [comment]
Original field name | New field name
------------------- | ----------------
`ApplicationRequestMethod` | `RequestMethod`
`ApplicationRequestOtherMethod` | `RequestOtherMethod`
`ApplicationRequestPostmarkDate` | (deleted)
`ApplicationRequestProcessedDate` | `RequestDate`
`ApplicationRequestReceivedDate` | (deleted)
`ApplicationRequestRejectionType` | `RequestStatusType`
(new) | `RequestStatusRejectedType`
`ApplicationRequestRejectionOtherType` | `RequestStatusOtherType`
`ApplicationRequestStatusType` | (deleted)
`ApplicationRequestType` | `RequestType`

**Comment by jungshadow** [comment]
This LGTM. @ctice5, @david-varas what do you think?

> My question is as to Pending under qualification status. Wouldn't that be similar to the cured issue we discussed previously?

@ctice5, I think we could see pending qualifications, but we wouldn't see cured as that isn't tracked (as far as I can tell).

**Comment by ctice5** [comment]
@jungshadow Ok, but how do they track that in their system? So if someone verifies the information would the voter have two entries, one that says pending and one that says qualified or do they have one singular entry that they flip to qualified?

Are there some states that don't leave you as pending but instead disqualify you, but notify you that you of what needs to be done to qualify?-->This I assume is something that David would want to know to determine the successfulness of FWAB (aka is it too hard to use so people are getting disqualified and not bothering to try again)

Am I making any sense?

**Comment by jungshadow** [comment]
> Ok, but how do they track that in their system? So if someone verifies the information would the voter have two entries, one that says pending and one that says qualified or do they have one singular entry that they flip to qualified? Are we also tracking why it was pending?

I'm unaware of the underlying process as to how it's being tracked, but my understanding from the conversations we have is that an FPCA might be in a pending state due to missing information, but, when an FPCA is cured, it overwrites the original pending record, so we wouldn't know what transactions flipped from `pending` to `qualified` (NB: assuming `pending` and `qualified` are the enumerations we pick). We'd just see the `qualified` transactions.

> Are there some states that don't leave you as pending but instead disqualify you, but notify you that you of what needs to be done to qualify?

Yes. Those are what the previous standard captured in some places. There are rejected FPCAs. FWABs can also be ballots and registrations so that example gets a little hairy.

> Am I making any sense?

Nope 😉 (Of course you are)
