### ISSUE TITLE
BallotReturn fields should be renamed with the BallotReceived prefix

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#33]
Since the entire standard is built from the perspective of the election official, the fields `BallotReturnDate`, `BallotReturnType`, and `BallotReturnOtherType` should be renamed to `BallotReceivedDate`, `BallotReceivedType`, and `BallotReceivedOtherType`, respectively.

**Comment by JDziurlaj** [comment]
Will make change, but use the `Method` suffix instead of `Type`. See #32.
