### ISSUE TITLE
Expand RequestStatusType to handle cancellations

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#38]
Certain jurisdictions have administrative processes around ballot requests that fall outside the three current states of `RequestStatusType`:

- accepted
- pending
- rejected

For example, a voter might ask to cancel their ballot request or take an action that causes the election official to cancel an existing ballot request; neither of which is the ballot request being "rejected." The proposal is to add a "cancelled" status to the existing enumerations. The definition could be:

> **cancelled**, which signifies that the request has been cancelled by a voter's direct or indirect action

**Comment by JDziurlaj** [comment]
Do we care that we can't track the state transitions? NB: I wasn't sure if you could move from `accepted` to `cancelled`.

![OVI](https://user-images.githubusercontent.com/7104454/78792818-9e306280-797f-11ea-9b52-5a2f90c356c6.png)

**Comment by jungshadow** [comment]
@JDziurlaj To be honest, they can't track the state transitions. They may have a state and reason when it's pending, but once it's cured, that first state is lost to the ether.
